// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { NearestData, NearestErrors, NearestResponses, RouteData, RouteErrors, RouteResponses, TableData, TableErrors, TableResponses, TripData, TripErrors, TripResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const nearest = <ThrowOnError extends boolean = false>(options: Options<NearestData, ThrowOnError>): RequestResult<NearestResponses, NearestErrors, ThrowOnError> => (options.client ?? client).get<NearestResponses, NearestErrors, ThrowOnError>({ url: '/nearest/{version}/{profile}/{coordinate}.json', ...options });

export const route = <ThrowOnError extends boolean = false>(options: Options<RouteData, ThrowOnError>): RequestResult<RouteResponses, RouteErrors, ThrowOnError> => (options.client ?? client).get<RouteResponses, RouteErrors, ThrowOnError>({ url: '/route/{version}/{profile}/{coordinates}', ...options });

export const table = <ThrowOnError extends boolean = false>(options: Options<TableData, ThrowOnError>): RequestResult<TableResponses, TableErrors, ThrowOnError> => (options.client ?? client).get<TableResponses, TableErrors, ThrowOnError>({ url: '/table/{version}/{profile}/{coordinates}', ...options });

export const trip = <ThrowOnError extends boolean = false>(options: Options<TripData, ThrowOnError>): RequestResult<TripResponses, TripErrors, ThrowOnError> => (options.client ?? client).get<TripResponses, TripErrors, ThrowOnError>({ url: '/trip/{version}/{profile}/{coordinates}', ...options });
