// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://router.project-osrm.org' | 'https://routing.openstreetmap.de/routed-car' | 'https://routing.openstreetmap.de/routed-bike' | 'https://routing.openstreetmap.de/routed-foot' | (string & {});
};

export type ApiResponse = {
    code: 'Ok' | 'InvalidUrl' | 'InvalidService' | 'InvalidVersion' | 'InvalidOptions' | 'InvalidQuery' | 'InvalidValue' | 'NoSegment' | 'TooBig' | 'NoRoute' | 'NoTable' | 'NotImplemented' | 'NoTrips';
    message?: string;
    data_version?: string;
};

export type NearestResponse = ApiResponse & {
    waypoints: Array<NearestWaypoint>;
};

export type RouteResponse = ApiResponse & {
    waypoints: Array<Waypoint>;
    routes: Array<Route>;
};

export type TableResponse = ApiResponse & {
    /**
     * array of arrays that stores the matrix in row-major order. durations[i][j] gives the travel time from the i-th waypoint to the j-th waypoint. Values are given in seconds.
     */
    durations: Array<Array<number>>;
    distances: Array<Array<number>>;
    sources: Array<Waypoint>;
    destinations: Array<Waypoint>;
    fallback_speed_cells: Array<Array<number>>;
};

export type TripResponse = ApiResponse & {
    waypoints: Array<TripWaypoint>;
    trips: Array<Route>;
};

export type Route = {
    /**
     * The distance traveled by the route, in float meters.
     */
    distance: number;
    /**
     * The estimated travel time, in float number of seconds.
     */
    duration: number;
    geometry: string;
    weight: number;
    weight_name: string;
    legs: Array<RouteLeg>;
};

export type RouteLeg = {
    /**
     * The distance traveled by the route, in float meters.
     */
    distance: number;
    /**
     * The estimated travel time, in float number of seconds.
     */
    duration: number;
    weight: number;
    summary: string;
    steps: Array<RouteStep>;
    annotation: Annotation;
};

export type RouteStep = {
    /**
     * The distance traveled by the route, in float meters.
     */
    distance: number;
    /**
     * The estimated travel time, in float number of seconds.
     */
    duration: number;
    geometry: string;
    weight: number;
    name: string;
    ref: string;
    pronunciation: string;
    destinations: {
        [key: string]: unknown;
    };
    exits: {
        [key: string]: unknown;
    };
    mode: string;
    maneuver: StepManeuver;
    intersections: Array<Intersection>;
    rotary_name: string;
    rotary_pronunciation: string;
    driving_side: 'left' | 'right';
};

export type Annotation = {
    /**
     * The distance, in metres, between each pair of coordinates
     */
    distance: Array<number>;
    /**
     * The duration between each pair of coordinates, in seconds
     */
    duration: Array<number>;
    datasources: Array<number>;
    nodes: Array<number>;
    weight: Array<number>;
    speed: Array<number>;
    metadata: {
        datasource_names: Array<string>;
    };
};

export type StepManeuver = {
    location: Array<number>;
    bearing_before: number;
    bearing_after: number;
    type: string;
    modifier: string;
    exit: number;
};

export type Intersection = {
    location: Array<number>;
    bearings: Array<number>;
    classes: Array<string>;
    entry: Array<unknown>;
    in: number;
    out: number;
    lanes: Array<Lane>;
};

export type Lane = {
    indications: Array<string>;
    valid: boolean;
};

export type Waypoint = {
    name: string;
    location: Array<number>;
    distance: number;
    hint: string;
};

export type NearestWaypoint = Waypoint & {
    nodes: Array<number>;
};

export type TripWaypoint = Waypoint & {
    trips_index: number;
    waypoint_index: number;
};

export type NearestData = {
    body?: never;
    path: {
        /**
         * Version of the protocol implemented by the service. v1 for all OSRM 5.x installations
         */
        version: string;
        /**
         * Mode of transportation, is determined statically by the Lua profile that is used to prepare the data using osrm-extract. Typically car, bike or foot if using one of the supplied profiles.
         */
        profile: string;
        coordinate: string;
    };
    query: {
        /**
         * Limits the search to segments with given bearing in degrees towards true north in clockwise direction.
         */
        bearings?: string;
        /**
         * Limits the search to given radius in meters.
         */
        radiuses?: string;
        /**
         * Adds a Hint to the response which can be used in subsequent requests, see hints parameter.
         */
        generate_hints?: boolean;
        /**
         * Hint from previous request to derive position in street network.
         */
        hints?: string;
        /**
         * Keep waypoints on curb side.
         */
        approaches?: string;
        /**
         * Additive list of classes to avoid, order does not matter.
         */
        exclude?: string;
        /**
         * Number of nearest segments that should be returned.
         */
        number: number;
    };
    url: '/nearest/{version}/{profile}/{coordinate}.json';
};

export type NearestErrors = {
    /**
     * Error
     */
    400: ApiResponse;
};

export type NearestError = NearestErrors[keyof NearestErrors];

export type NearestResponses = {
    /**
     * OK
     */
    200: NearestResponse;
};

export type NearestResponse2 = NearestResponses[keyof NearestResponses];

export type RouteData = {
    body?: never;
    path: {
        /**
         * Version of the protocol implemented by the service. v1 for all OSRM 5.x installations
         */
        version: string;
        /**
         * Mode of transportation, is determined statically by the Lua profile that is used to prepare the data using osrm-extract. Typically car, bike or foot if using one of the supplied profiles.
         */
        profile: string;
        coordinates: string;
    };
    query?: {
        /**
         * Limits the search to segments with given bearing in degrees towards true north in clockwise direction.
         */
        bearings?: string;
        /**
         * Limits the search to given radius in meters.
         */
        radiuses?: string;
        /**
         * Adds a Hint to the response which can be used in subsequent requests, see hints parameter.
         */
        generate_hints?: boolean;
        /**
         * Hint from previous request to derive position in street network.
         */
        hints?: string;
        /**
         * Keep waypoints on curb side.
         */
        approaches?: string;
        /**
         * Additive list of classes to avoid, order does not matter.
         */
        exclude?: string;
        /**
         * Search for alternative routes. Passing a number alternatives=n searches for up to n alternative routes.
         */
        alternatives?: boolean | number;
        /**
         * Returned route steps for each route leg
         */
        steps?: boolean;
        /**
         * Returns additional metadata for each coordinate along the route geometry.
         */
        annotations?: true | false | 'nodes' | 'distance' | 'duration' | 'datasources' | 'weight' | 'speed';
        /**
         * Returned route geometry format (influences overview and per step)
         */
        geometries?: 'polyline' | 'polyline6' | 'geojson';
        /**
         * Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all.
         */
        overview?: 'simplified' | 'full' | false;
        /**
         * Forces the route to keep going straight at waypoints constraining uturns there even if it would be faster. Default value depends on the profile.
         */
        continue_straight?: 'default' | true | false;
        /**
         * Treats input coordinates indicated by given indices as waypoints in returned Match object. Default is to treat all input coordinates as waypoints.
         */
        waypoints?: string;
    };
    url: '/route/{version}/{profile}/{coordinates}';
};

export type RouteErrors = {
    /**
     * Error
     */
    400: ApiResponse;
};

export type RouteError = RouteErrors[keyof RouteErrors];

export type RouteResponses = {
    /**
     * OK
     */
    200: RouteResponse;
};

export type RouteResponse2 = RouteResponses[keyof RouteResponses];

export type TableData = {
    body?: never;
    path: {
        /**
         * Version of the protocol implemented by the service. v1 for all OSRM 5.x installations
         */
        version: string;
        /**
         * Mode of transportation, is determined statically by the Lua profile that is used to prepare the data using osrm-extract. Typically car, bike or foot if using one of the supplied profiles.
         */
        profile: string;
        coordinates: string;
    };
    query?: {
        /**
         * Limits the search to segments with given bearing in degrees towards true north in clockwise direction.
         */
        bearings?: string;
        /**
         * Limits the search to given radius in meters.
         */
        radiuses?: string;
        /**
         * Adds a Hint to the response which can be used in subsequent requests, see hints parameter.
         */
        generate_hints?: boolean;
        /**
         * Hint from previous request to derive position in street network.
         */
        hints?: string;
        /**
         * Keep waypoints on curb side.
         */
        approaches?: string;
        /**
         * Additive list of classes to avoid, order does not matter.
         */
        exclude?: string;
        /**
         * Use location with given index as source.
         */
        sources?: string;
        /**
         * Use location with given index as destination.
         */
        destinations?: string;
    };
    url: '/table/{version}/{profile}/{coordinates}';
};

export type TableErrors = {
    /**
     * Error
     */
    400: ApiResponse;
};

export type TableError = TableErrors[keyof TableErrors];

export type TableResponses = {
    /**
     * OK
     */
    200: TableResponse;
};

export type TableResponse2 = TableResponses[keyof TableResponses];

export type TripData = {
    body?: never;
    path: {
        /**
         * Version of the protocol implemented by the service. v1 for all OSRM 5.x installations
         */
        version: string;
        /**
         * Mode of transportation, is determined statically by the Lua profile that is used to prepare the data using osrm-extract. Typically car, bike or foot if using one of the supplied profiles.
         */
        profile: string;
        coordinates: string;
    };
    query?: {
        /**
         * Limits the search to segments with given bearing in degrees towards true north in clockwise direction.
         */
        bearings?: string;
        /**
         * Limits the search to given radius in meters.
         */
        radiuses?: string;
        /**
         * Adds a Hint to the response which can be used in subsequent requests, see hints parameter.
         */
        generate_hints?: boolean;
        /**
         * Hint from previous request to derive position in street network.
         */
        hints?: string;
        /**
         * Keep waypoints on curb side.
         */
        approaches?: string;
        /**
         * Additive list of classes to avoid, order does not matter.
         */
        exclude?: string;
        /**
         * Returned route is a roundtrip (route returns to first location)
         */
        roundtrip?: boolean;
        /**
         * Returned route starts at any or first coordinate
         */
        source?: 'any' | 'first';
        /**
         * Returned route ends at any or last coordinate
         */
        destination?: 'any' | 'last';
        /**
         * Returned route instructions for each trip
         */
        steps?: boolean;
        /**
         * Returns additional metadata for each coordinate along the route geometry.
         */
        annotations?: 'true' | 'false' | 'nodes' | 'distance' | 'duration' | 'datasources' | 'weight' | 'speed';
        /**
         * Returned route geometry format (influences overview and per step)
         */
        geometries?: 'polyline' | 'polyline6' | 'geojson';
        /**
         * Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all.
         */
        overview?: 'simplified' | 'full' | 'false';
    };
    url: '/trip/{version}/{profile}/{coordinates}';
};

export type TripErrors = {
    /**
     * Error
     */
    400: ApiResponse;
};

export type TripError = TripErrors[keyof TripErrors];

export type TripResponses = {
    /**
     * OK
     */
    200: TripResponse;
};

export type TripResponse2 = TripResponses[keyof TripResponses];
